@echo off
echo Stopping all Python processes...
taskkill /F /IM python.exe

echo Clearing system-wide OPENAI_API_KEY environment variable...
set "OPENAI_API_KEY="

echo Adding write permissions to database file...
icacls db.sqlite3 /grant Everyone:F

echo Starting Django server with a clean environment...
python manage.py runserver 